name: Publish to GitHub Pages

on:
  push:
    branches: [ master ]
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install markdown-to-html
      run: |
        npm i -g git+https://github.com/Kroid/markdown-to-html.git

    - name: Generate HTML
      run: markdown-to-html -t ./template.html

    - name: Publish
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
